#!/usr/bin/dumb-init /bin/bash

set -xe

# gitlab-ci-multi-runner data directory
DATA_DIR="/etc/gitlab-runner"
CONFIG_FILE=${CONFIG_FILE:-$DATA_DIR/config.toml}
# custom certificate authority path
CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-$DATA_DIR/certs/ca.crt}
LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

# check docker sock mounted
if [ -e /var/run/docker.sock ];then
  GID=`ls -n /var/run/docker.sock | cut  -d ' ' -f 4`
  groupadd -g $GID docker
  usermod -G $GID gitlab-runner
fi

# gitlab-runner dir
if [ -d /home/gitlab-runner/builds ];then
  chmod 777 /home/gitlab-runner/builds
fi

# copy config from k8s configmap
[ -e /config/config.toml ] && \
  cp /config/config.toml ${CONFIG_FILE}

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  # update the ca if the custom ca is different than the current
  cmp --silent "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
fi

# Register the runner
gitlab-ci-multi-runner register --non-interactive \
  --url $GITLAB_URL \
  --executor shell

# Start the runner
exec gitlab-ci-multi-runner run  --user=gitlab-runner \
  --working-directory=/home/gitlab-runner
